# Generated by Django 4.1 on 2023-06-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='imgage',
            new_name='image',
        ),
    ]
