# Generated by Django 4.1 on 2023-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_imgage_aboutus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='socia_link',
        ),
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://www.facebook.com/', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://www.instagram.com/', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(blank=True, default='https://www.linkedin.com/', null=True),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
