# Generated by Django 4.1 on 2023-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
