# Generated by Django 4.1 on 2023-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
